//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Input_ActionSet_TiltBrush p_TiltBrush;
        
        private static SteamVR_Input_ActionSet_mixedreality p_mixedreality;
        
        public static SteamVR_Input_ActionSet_TiltBrush TiltBrush
        {
            get
            {
                return SteamVR_Actions.p_TiltBrush.GetCopy<SteamVR_Input_ActionSet_TiltBrush>();
            }
        }
        
        public static SteamVR_Input_ActionSet_mixedreality mixedreality
        {
            get
            {
                return SteamVR_Actions.p_mixedreality.GetCopy<SteamVR_Input_ActionSet_mixedreality>();
            }
        }
        
        private static void StartPreInitActionSets()
        {
            SteamVR_Actions.p_TiltBrush = ((SteamVR_Input_ActionSet_TiltBrush)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_TiltBrush>("/actions/TiltBrush")));
            SteamVR_Actions.p_mixedreality = ((SteamVR_Input_ActionSet_mixedreality)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_mixedreality>("/actions/mixedreality")));
            Valve.VR.SteamVR_Input.actionSets = new Valve.VR.SteamVR_ActionSet[] {
                    SteamVR_Actions.TiltBrush,
                    SteamVR_Actions.mixedreality};
        }
    }
}
